version: '2.1'
services:
  ####### ELK Stack ############
  elasticsearch:
    image: elasticsearch:latest
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 10

  kibana:
    image: kibana:latest
    volumes:
      -  ../centralized-logging/kibana/kibana.yml:/opt/kibana/config/kibana.yml
    ports:
      - 5601:5601
    depends_on:
      elasticsearch:
        condition: service_healthy

  logstash:
    image: logstash:latest
    command: bash -c "logstash -f /etc/logstash/conf.d/logstash.conf"
    volumes:
      - ../centralized-logging/logstash/:/etc/logstash/conf.d
    ports:
      - 5044:5044
      - 9600:9600
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9600"]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      elasticsearch:
        condition: service_healthy

  ####### Common Services ############
  config-server:
    build: ../config-server
    mem_limit: 200000000
    ports:
      - 8888:8888

  api-gateway:
    build: ../api-gateway
    mem_limit: 200000000
    ports:
      - 8080:8080
    depends_on:
      config-server:
        condition: service_healthy

  ####### Microservices ############
  inventory-mongodb:
    image: mongo:latest
    ports:
      - 27017:27017

  inventory-filebeat:
    image: docker.elastic.co/beats/filebeat:6.2.4
    volumes:
      - ../inventory-service/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ../inventory-service/logs/:/logs/
    depends_on:
      logstash:
        condition: service_healthy

  inventory-service:
    build: ../inventory-service
    mem_limit: 200000000
    ports:
      - 8081:8081
    volumes:
      - ../inventory-service/logs/:/logs/
    depends_on:
      config-server:
        condition: service_healthy

  shopping-cart:
      build: ../shopping-cart
      mem_limit: 200000000
      ports:
        - 8089:8089
      depends_on:
        config-server:
          condition: service_healthy

  review-service:
    build: ../review-service
    mem_limit: 200000000
    ports:
      - 8082:8082
    depends_on:
      config-server:
        condition: service_healthy

  order-mongodb:
    image: mongo:latest
    ports:
      - 27001:27017

  order-filebeat:
    image: docker.elastic.co/beats/filebeat:6.2.4
    volumes:
      - ../order-service/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ../order-service/logs/:/logs/
    depends_on:
      logstash:
        condition: service_healthy

  order-service:
    build: ../order-service
    mem_limit: 200000000
    ports:
      - 8099:8099
    volumes:
      - ../order-service/logs/:/logs/
    depends_on:
      config-server:
        condition: service_healthy

  recommendation-service:
    build: ../recommendation-service
    mem_limit: 200000000
    ports:
      - 8077:8077
    depends_on:
      config-server:
        condition: service_healthy
